"""vacancy ai_instructions

Revision ID: 214354462225
Revises: 223dfb467650
Create Date: 2026-06-12 05:37:07.211815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '214354462225'
down_revision: Union[str, None] = '223dfb467650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('ai_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'ai_instructions')
    # ### end Alembic commands ###
