"""candidate language

Revision ID: 223dfb467650
Revises: 590056310da9
Create Date: 2026-06-12 04:46:03.035470
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '223dfb467650'
down_revision: Union[str, None] = '590056310da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'language')
    # ### end Alembic commands ###
