"""company profile + opaque vacancy token

Revision ID: 2ae4d27375ef
Revises: f52d4453f18a
Create Date: 2026-06-13 14:30:56.246189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ae4d27375ef'
down_revision: Union[str, None] = 'f52d4453f18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('organizations', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))

    # Backfill opaque deep-link tokens for vacancies still using the sequential job_<id>.
    import secrets
    import string

    alphabet = string.ascii_letters + string.digits
    conn = op.get_bind()
    rows = conn.execute(
        sa.text("SELECT id FROM vacancies WHERE deep_link_param LIKE 'job_%' OR deep_link_param IS NULL")
    ).fetchall()
    for (vid,) in rows:
        token = "".join(secrets.choice(alphabet) for _ in range(10))
        conn.execute(
            sa.text("UPDATE vacancies SET deep_link_param = :t WHERE id = :id"),
            {"t": token, "id": vid},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'about')
    # ### end Alembic commands ###
