"""cover letter

Revision ID: 590056310da9
Revises: a16d96765f1b
Create Date: 2026-06-11 23:44:40.581175
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '590056310da9'
down_revision: Union[str, None] = 'a16d96765f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter_text', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('cover_letter_file_path', sa.String(length=512), nullable=True))
    op.add_column('applications', sa.Column('cover_letter_filename', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('cover_letter_mime', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter_mime')
    op.drop_column('applications', 'cover_letter_filename')
    op.drop_column('applications', 'cover_letter_file_path')
    op.drop_column('applications', 'cover_letter_text')
    # ### end Alembic commands ###
