"""phase2 ats pipeline

Revision ID: a16d96765f1b
Revises: 3d2b55892f50
Create Date: 2026-06-10 09:42:26.031243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a16d96765f1b'
down_revision: Union[str, None] = '3d2b55892f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enums added via op.add_column are NOT auto-created by Alembic — create explicitly first.
    application_stage = postgresql.ENUM(
        'new', 'screening', 'shortlisted', 'test_task', 'interview', 'offer', 'hired',
        'rejected', 'withdrawn', name='application_stage',
    )
    application_stage.create(op.get_bind(), checkfirst=True)

    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('test_task', 'interview', 'offer', 'rejection', 'custom', name='template_type'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_org_id'), 'message_templates', ['org_id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('trigger', sa.Enum('on_scored', name='automation_trigger'), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('reject', 'shortlist', 'set_stage', 'send_template', name='automation_action'), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_org_id'), 'automation_rules', ['org_id'], unique=False)
    op.create_index(op.f('ix_automation_rules_vacancy_id'), 'automation_rules', ['vacancy_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('application_created', 'ai_scored', 'stage_changed', 'message_sent', 'message_received', 'test_submitted', 'test_graded', 'interview_scheduled', 'interview_canceled', 'offer_sent', 'rejected', 'note_added', 'consent_given', 'data_erased', name='activity_type'), nullable=False),
    sa.Column('actor', sa.Enum('user', 'system', 'candidate', name='activity_actor'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_application_id'), 'activities', ['application_id'], unique=False)
    op.create_index(op.f('ix_activities_org_id'), 'activities', ['org_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('calendly', 'manual', name='interview_provider'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('join_url', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'canceled', 'completed', name='interview_status'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_external_id'), 'interviews', ['external_id'], unique=False)
    op.create_index(op.f('ix_interviews_org_id'), 'interviews', ['org_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='message_direction'), nullable=False),
    sa.Column('channel', sa.Enum('telegram', name='message_channel'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('sent', 'failed', 'received', name='message_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_application_id'), 'messages', ['application_id'], unique=False)
    op.create_index(op.f('ix_messages_org_id'), 'messages', ['org_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_mime', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'graded', 'failed', name='submission_status'), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_application_id'), 'submissions', ['application_id'], unique=False)
    op.create_index(op.f('ix_submissions_org_id'), 'submissions', ['org_id'], unique=False)
    op.add_column('applications', sa.Column('stage', postgresql.ENUM('new', 'screening', 'shortlisted', 'test_task', 'interview', 'offer', 'hired', 'rejected', 'withdrawn', name='application_stage', create_type=False), nullable=False, server_default='new'))
    op.add_column('applications', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_applications_stage'), 'applications', ['stage'], unique=False)
    op.add_column('candidates', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidates', sa.Column('consent_version', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('delete_after', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_candidates_delete_after'), 'candidates', ['delete_after'], unique=False)
    op.add_column('organizations', sa.Column('calendly_token_enc', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('calendly_event_type_uri', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('calendly_scheduling_url', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('calendly_webhook_signing_key', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('logo_path', sa.String(length=512), nullable=True))
    op.add_column('organizations', sa.Column('brand_color', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('retention_days', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('privacy_notice', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'privacy_notice')
    op.drop_column('organizations', 'retention_days')
    op.drop_column('organizations', 'brand_color')
    op.drop_column('organizations', 'logo_path')
    op.drop_column('organizations', 'calendly_webhook_signing_key')
    op.drop_column('organizations', 'calendly_scheduling_url')
    op.drop_column('organizations', 'calendly_event_type_uri')
    op.drop_column('organizations', 'calendly_token_enc')
    op.drop_index(op.f('ix_candidates_delete_after'), table_name='candidates')
    op.drop_column('candidates', 'delete_after')
    op.drop_column('candidates', 'consent_version')
    op.drop_column('candidates', 'consent_at')
    op.drop_column('candidates', 'email')
    op.drop_index(op.f('ix_applications_stage'), table_name='applications')
    op.drop_column('applications', 'last_activity_at')
    op.drop_column('applications', 'decision_reason')
    op.drop_column('applications', 'stage')
    op.drop_index(op.f('ix_submissions_org_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_application_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_messages_org_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_application_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_interviews_org_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_external_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_activities_org_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_application_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_automation_rules_vacancy_id'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_org_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_message_templates_org_id'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
