"""application chat_open

Revision ID: f52d4453f18a
Revises: 214354462225
Create Date: 2026-06-12 06:34:52.268191
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f52d4453f18a'
down_revision: Union[str, None] = '214354462225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('chat_open', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'chat_open')
    # ### end Alembic commands ###
